include:
  - board: seeeduino_xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: roBa_L
  - board: seeeduino_xiao_ble
    shield: settings_reset
  # 既存のnRF52840 Dongleボードを使用
  - board: nrf52840dongle_nrf52840
    shield: roBa_dongle
