include:
  # roBa Right (Central) - studio snippet
  - board: seeeduino_xiao_ble
    shield: roBa/roBa_R
    snippet: studio-rpc-usb-uart

  # roBa Left (Remote)
  - board: seeeduino_xiao_ble
    shield: roBa/roBa_L

  # Settings Reset shield
  - board: seeeduino_xiao_ble
    shield: roBa/settings_reset

  # Holyiot NRF52840 Dongle
  - board: holyiot_nrf52840_dongle
