# build.yaml - ZMK v0.3 optimized build matrix
include:
  # roBa Right (Central) - studio snippet
  - board: seeeduino_xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart

  # roBa Left (Remote) - no snippet
  - board: seeeduino_xiao_ble
    shield: roBa_L

  # Settings Reset
  - board: seeeduino_xiao_ble
    shield: settings_reset

  # Holyiot NRF52840 Dongle
  - board: holyiot_nrf52840_dongle
