include:
  - board: seeeduino_xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: roBa_L
  - board: seeeduino_xiao_ble
    shield: settings_reset
  # nrf52840dongle用にUF2形式も生成
  - board: nrf52840dongle_nrf52840
    shield: roBa_dongle
    snippet: zmk-usb-uf2
